### ISSUE TITLE
Lines in the table for decoration

### ISSUE THREAD

**Issue by tanmoy27112000** [yamarkz/flutter_timetable_view#4]
**Is your feature request related to a problem? Please describe.**
Please can you add multiple lines in the containers so that it loos like this picture that I have attached,

**Describe the solution you'd like**
a simple showLines should toggle the lines visibility
![WhatsApp Image 2020-10-27 at 1 45 36 PM](https://user-images.githubusercontent.com/22212661/97276866-c4571a80-185d-11eb-8303-8229f39551e7.jpeg)

**Describe alternatives you've considered**

**Additional context**

**Comment by yamarkz** [comment]
@tanmoy27112000 
Thanks, that's a very good suggestion. I will be a candidate for implementation.
Are you using this package?

**Comment by tanmoy27112000** [comment]
yes I am using this project for my app. Please if you can integrate this feature it will help me a lot.

**Comment by yamarkz** [comment]
@tanmoy27112000 
This feature was released in 0.2.0.
Please update the package and try it out.
